spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false #关闭自我保护功能
    eviction-interval-timer-in-ms: 4000 #//清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: node1
  client:
    service-url:
      defaultZone: http://node4:8761/eureka/,http://node5:8761/eureka/
---
spring:
  profiles: peer4
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: node4
  client:
    service-url:
      defaultZone: http://node1:8761/eureka/,http://node5:8761/eureka/
---
spring:
  profiles: peer5
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: node5
  client:
    service-url:
      defaultZone: http://node4:8761/eureka/,http://node1:8761/eureka/